repos:
  - repo: local
    hooks:
      # https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: ruff_format
        name: ruff_format 
        entry: poetry run ruff format
        language: system
        types: [python]
        files: "^signal_generation/"
        exclude: '^(signal_generation/openfusiontoolkit/|signal_generation/SPARC_Mesh_Test.py|signal_generation/header_signal_generation.py)$'
        # exclude: "^signal_generation/openfusiontoolkit/"
      - id: ruff_check
        name: ruff_check
        entry: poetry run ruff check --fix
        language: system
        types: [python]
        files: "^signal_generation/"
        exclude: '^(signal_generation/openfusiontoolkit/|signal_generation/SPARC_Mesh_Test.py|signal_generation/header_signal_generation.py)$'
        # exclude: "^signal_generation/openfusiontoolkit/"
